[package]
name = "slang-sys"
description = "Thin Rust bindings for the upstream slang SystemVerilog frontend"
version = "11.0.0"                                                               # aligned with slang version
edition = "2024"
license = "MIT"
build = "build.rs"

[dependencies]
cxx = { version = "1.0.124", features = ["c++20"] }
tracing.workspace = true

[build-dependencies]
cmake = "0.1.50"
cxx-build = "1.0.124"
