#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


def screaming_snake(name: str) -> str:
    parts = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", name)
    return "_".join(part.upper() for part in parts)


def load_trivia_kind_names(path: Path) -> list[str]:
    kinds = []
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        kinds.append(line)
    return kinds


def render_trivia_kind(kinds: list[str]) -> str:
    constants = []
    debug_arms = []
    all_values = []

    for index, kind in enumerate(kinds):
        const_name = screaming_snake(kind)
        constants.append(f"    pub const {const_name}: Self = Self({index});")
        debug_arms.append(f'            Self::{const_name} => "{kind}",')
        all_values.append(f"Self::{const_name}")

    return f"""#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct TriviaKind(u8);

impl TriviaKind {{
{chr(10).join(constants)}

    pub const ALL: &'static [Self] = &[{", ".join(all_values)}];

    #[inline]
    pub const fn from_raw(raw: u8) -> Self {{
        Self(raw)
    }}

    #[inline]
    pub const fn as_raw(self) -> u8 {{
        self.0
    }}

    #[inline]
    pub const fn is_unknown(self) -> bool {{
        self.0 == Self::UNKNOWN.0
    }}
}}

impl fmt::Debug for TriviaKind {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        let name = match *self {{
{chr(10).join(debug_arms)}
            _ => return write!(f, "TriviaKind({{}})", self.0),
        }};
        f.write_str(name)
    }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Rust TriviaKind from slang triviakinds.txt")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    output = "\n".join(
        [
            "// This file is generated by crates/slang-sys/scripts/generate_trivia_kind.py.",
            "// Do not edit by hand.",
            "",
            "use std::fmt;",
            "",
            render_trivia_kind(load_trivia_kind_names(args.input)),
        ]
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)


if __name__ == "__main__":
    main()
