#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


def screaming_snake(name: str) -> str:
    parts = re.findall(r"[A-Z]+(?=[A-Z][a-z]|\d|$)|[A-Z]?[a-z]+|\d+", name)
    return "_".join(part.upper() for part in parts)


def load_syntax_kind_names(path: Path) -> list[str]:
    kind_map = {}
    current_type = None
    current_kind_base = None
    current_tags = []

    def finish_type():
        nonlocal current_type, current_kind_base, current_tags
        if current_type is None:
            return

        tags = dict(tag.split("=", 1) for tag in current_tags)
        is_final = tags.get("final", "true") != "false"
        is_multi_kind = tags.get("multiKind") == "true"
        if is_final and not is_multi_kind:
            if current_type in kind_map:
                raise RuntimeError(f"duplicate syntax kind: {current_type}")
            kind_map[current_type] = current_type + "Syntax"

        current_type = None
        current_kind_base = None
        current_tags = []

    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if line.startswith("//"):
            continue

        if not line or line == "empty":
            current_kind_base = None
            finish_type()
            continue

        if current_kind_base is not None:
            for kind in line.split():
                if kind in kind_map:
                    raise RuntimeError(f"duplicate syntax kind: {kind}")
                kind_map[kind] = current_kind_base + "Syntax"
            continue

        if current_type is not None:
            continue

        if line.startswith("kindmap<"):
            current_kind_base = line[len("kindmap<") : line.index(">")]
            continue

        parts = line.split()
        current_type = parts[0]
        current_tags = parts[1:]

    finish_type()

    return ["Unknown", *sorted(kind_map.keys())]


def render_syntax_kind(kinds: list[str]) -> str:
    constants = []
    debug_arms = []
    all_values = []

    for index, kind in enumerate(kinds):
        const_name = screaming_snake(kind)
        constants.append(f"    pub const {const_name}: Self = Self({index});")
        debug_arms.append(f'            Self::{const_name} => "{kind}",')
        all_values.append(f"Self::{const_name}")

    return f"""#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct SyntaxKind(u16);

impl SyntaxKind {{
{chr(10).join(constants)}

    pub const ALL: &'static [Self] = &[{", ".join(all_values)}];

    #[inline]
    pub const fn from_raw(raw: u16) -> Self {{
        Self(raw)
    }}

    #[inline]
    pub const fn as_raw(self) -> u16 {{
        self.0
    }}

    #[inline]
    pub const fn is_unknown(self) -> bool {{
        self.0 == Self::UNKNOWN.0
    }}
}}

impl fmt::Debug for SyntaxKind {{
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {{
        let name = match *self {{
{chr(10).join(debug_arms)}
            _ => return write!(f, "SyntaxKind({{}})", self.0),
        }};
        f.write_str(name)
    }}
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Rust SyntaxKind from slang syntax.txt")
    parser.add_argument("--input", type=Path, required=True)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()

    output = "\n".join(
        [
            "// This file is generated by crates/slang-sys/scripts/generate_syntax_kind.py.",
            "// Do not edit by hand.",
            "",
            "use std::fmt;",
            "",
            render_syntax_kind(load_syntax_kind_names(args.input)),
        ]
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(output)


if __name__ == "__main__":
    main()
