[package]
name = "syntax"
version = "0.0.0"
description = "Syntax facade and utilities over slang-sys"

edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
either.workspace = true
serde.workspace = true
smol_str.workspace = true
slang_sys = { package = "slang-sys", path = "../slang-sys" }
utils.workspace = true
